import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { status } = useSession();

  const { data: games } = api.game.getAll.useQuery(undefined, {
    refetchOnWindowFocus: false,
    staleTime: Infinity,
  });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-dark-teal">
        <div>
          Games we support:
          <ul>
            {games?.map((game) => (
              <li key={game.id}>
                <p>{game.title}</p>
              </li>
            ))}
          </ul>
        </div>
        <button
          className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
          onClick={
            status === "authenticated"
              ? () => void signOut()
              : () => void signIn()
          }
        >
          {status === "authenticated" ? "Sign out" : "Sign in"}
        </button>
      </main>
    </>
  );
};

export default Home;
