name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: "https://www.fakedb.com"

      GOOGLE_CLIENT_ID: "fake client id"
      GOOGLE_CLIENT_SECRET: "fake client secret"

      NEXTAUTH_SECRET: "fake secret"
      NEXTAUTH_URL: "fake auth url"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: TypeScript type checking
        run: npm run typecheck

      - name: Linting
        run: npm run lint

      - name: Testing
        run: npm run test
